version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./app-php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./app-php/src:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin123
            MYSQL_DATABASE: phpcrud
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin123
        ports:
            - "9906:3306"