version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        hostname: php-apache
        build:
            context: ./app-php
            dockerfile: dockerfile
        depends_on:
            - db
        volumes:
            - ./app-php/src:/var/www/html/
        ports:
            - "8000:80"
    db:
        container_name: db
        hostname: mysqlDB
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin123
            MYSQL_DATABASE: phpcrud
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin123
        ports:
            - "9906:3306"
        volumes:
          - ./mysql:/docker-entrypoint-initdb.d
          - ./db:/var/lib/mysql
    php-myadmin:
        container_name: php-myadmin
        hostname: php-myadmin
        image: phpmyadmin:5.1.1-apache
        restart: always
        depends_on:
            - db
        ports: 
            - "8080:80"
        environment: 
            PMA_HOST: db